-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db_patches/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE wikimedia_campaign_events_grant (
  wceg_id BIGSERIAL NOT NULL,
  wceg_event_id BIGINT NOT NULL,
  wceg_grant_id TEXT NOT NULL,
  wceg_grant_agreement_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(wceg_id)
);

CREATE UNIQUE INDEX wceg_event_id ON wikimedia_campaign_events_grant (wceg_event_id);
